import { Inter } from 'next/font/google'
import './globals.css'
import Panner from '@/components/Panner'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Skillbridge',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='py-4 px-5 bg-main-gray'>
      <body className={inter.className}>
        <Panner />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
